# This workflow will do a clean installation of node dependencies, cache/restore them, build and upload /out folder to Amazon S3
name: mobiplus

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: AKIAY7WCVA5OZO66XEFO
          aws-secret-access-key: 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
          aws-region: ap-southeast-1
      - name: Copy files to S3 with the AWS CLI
        run: |
          aws s3 sync ./out s3://91d68dad-cc10-4039-be81-fd3d261a8cf8/
